export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  CHECK_USER_SESSION: "user/CHECK_USER_SESSION",
  GOOGLE_SIGN_IN_LOADING: "user/GOOGLE_SIGN_IN_LOADING",
  EMAIL_SIGN_IN_LOADING: "user/EMAIL_SIGN_IN_LOADING",
  SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'user/SIGN_IN_FAILED'
};
