export const SINGLE_BRAND_ACTION_TYPES = {
    FETCH_SINGLE_BRAND_LOADING: 'singleBrand/FETCH_SINGLE_BRAND_LOADING',
    FETCH_SINGLE_BRAND_SUCCESS: 'singleBrand/FETCH_SINGLE_BRAND_SUCCESS',
    FETCH_SINGLE_BRAND_FAILED: 'singleBrand/FETCH_SINGLE_BRAND_FAILED',
}