export enum ORDERS_ACTION_TYPES {
    FETCH_ALL_ORDERS_LOADING = "orders/FETCH_ALL_ORDERS_LOADING",
    FETCH_ALL_ORDERS_SUCCESS = "orders/FETCH_ALL_ORDERS_SUCCESS",
    FETCH_ALL_ORDERS_FAILED = "orders/FETCH_ALL_ORDERS_FAILED",
    FETCH_ORDER_BY_ID_LOADING = "orders/FETCH_ORDER_BY_ID_LOADING",
    FETCH_ORDER_BY_ID_SUCCESS = "orders/FETCH_ORDER_BY_ID_SUCCESS",
    FETCH_ORDER_BY_ID_FAILED = "orders/FETCH_ORDER_BY_ID_FAILED",
  };
  