export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_LOADING: "products/FETCH_PRODUCTS_LOADING",
  FETCH_PRODUCTS_SUCCESS: "products/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "products/FETCH_PRODUCTS_FAILED",
  FETCH_PRODUCTS_BY_VENDOR_LOADING: "products/FETCH_PRODUCTS_BY_VENDOR_LOADING",
  FETCH_PRODUCTS_BY_VENDOR_SUCCESS: "products/FETCH_PRODUCTS_BY_VENDOR_SUCCESS",
  FETCH_PRODUCTS_BY_VENDOR_FAILED: "products/FETCH_PRODUCTS_VENDOR_FAILED",
};
