export const PRODUCTS_ACTION_TYPES = {
  FETCH_PRODUCTS_LOADING: "products/FETCH_PRODUCTS_LOADING",
  FETCH_PRODUCTS_SUCCESS: "products/FETCH_PRODUCTS_SUCCESS",
  FETCH_PRODUCTS_FAILED: "products/FETCH_PRODUCTS_FAILED",
};
