export const CUSTOMERS_ACTION_TYPES = {
    FETCH_ALL_CUSTOMERS_LOADING: "customers/FETCH_ALL_CUSTOMERS_LOADING",
    FETCH_ALL_CUSTOMERS_SUCCESS: "customers/FETCH_ALL_CUSTOMERS_SUCCESS",
    FETCH_ALL_CUSTOMERS_FAILED: "customers/FETCH_ALL_CUSTOMERS_FAILED",
  };
  