export const CUSTOMERS_ACTION_TYPES = {
    FETCH_ALL_CUSTOMERS_LOADING: "customers/FETCH_ALL_CUSTOMERS_LOADING",
    FETCH_ALL_CUSTOMERS_SUCCESS: "customers/FETCH_ALL_CUSTOMERS_SUCCESS",
    FETCH_ALL_CUSTOMERS_FAILED: "customers/FETCH_ALL_CUSTOMERS_FAILED",
    ADD_CUSTOMER_LOADING: "customers/ADD_CUSTOMER_LOADING",
    ADD_CUSTOMER_SUCCESS: "customers/ADD_CUSTOMER_SUCCESS",
    ADD_CUSTOMER_FAILED: "customers/ADD_CUSTOMER_FAILED",
  };
  