export const BRANDS_ACTION_TYPES = {
    FETCH_BRANDS_LOADING: 'brand/FETCH_BRANDS_LOADING',
    FETCH_BRANDS_SUCCESS: 'brand/FETCH_BRANDS_SUCCESS',
    FETCH_BRANDS_FAILED: 'brand/SET_FETCH_BRANDS_FAILED',
}