export enum PAYMENTS_ACTION_TYPES {
  SET_CLIENT_SECRET_LOADING = "payments/SET_CLIENT_SECRET_LOADING",
  SET_CLIENT_SECRET_SUCCESS = "payments/SET_CLIENT_SECRET_SUCCESS",
  SET_CLIENT_SECRET_FAILED = "payments/SET_CLIENT_SECRET_FAILED",
}
